name: NickNames
version: 0.1.0
description: A plugin to change the nick names of users.
author: Halo4356
main: com.rafuse.minecraft.NickNames.Main
commands:
  nick:
    description: Set a nickname for a target user.
    usage: /nick [Player]