name: NickNames
version: 0.5.8
description: A plugin to change the nick names of users.
author: Halo4356
main: com.rafuse.minecraft.NickNames.Main
commands:
  nick:
    description: Set a nickname for a target user.
    usage: /nick [Player] [Nickname], /nick [Nickname]
  reset:
    description: Reset your or another person's nickname.
    usage: /reset, /reset [Player]
  color:
    description: Set your or another person's name's color.
    usage: /color [color code], /color [Player] [color code]
  colour:
    description: Set your or another person's name's color.
    usage: /colour [colour code], /colour [Player] [colour code]
  realnicks:
    description: Lists online players, with real names and nick names.
    usage: /realnicks
permissions:
  nicknames.nick:
    description: Permission on nick yourself
    default: op
  nicknames.nick.other:
    desciption: Permission to nick others
    default: op
  nicknames.reset:
    description: Reset your name to normal
    default: op
  nicknames.reset.other:
    description: Reset other peoples' names
    default: op
  nicknames.color:
    description: Color your name
    default: op
  nicknames.color.other:
    desciption: Color another person's name
    default: op
  nicknames.realnicks:
    decsription: Check online true names